name : subbu-Assignment
on : 
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: mkdir assignment
            - name: Create a file and add content
              run: |
                echo "This is my assignment file." > assignment/assignment.txt
                echo "I am learning GitHub Actions." >> assignment/assignment.txt   
                